### PR TITLE
upgrade libdparse

### PR DESCRIPTION
**Pull request by WebFreak001**
adds support for interpolated strings

### CODE REVIEW

**Review by LightBender — APPROVED** [review]

**Comment by rikkimax** [comment]
I don't understand how this is passing.

```
    Cleaning artifacts for package dscanner at C:\Users\alpha\AppData\Local\dub\cache\dscanner\0.16.0-beta.4+commit.18.g3a87c65
   Upgrading project in Q:\Misc Software\D-Dev-Tools\D-Scanner\
     Warning Warning: License in sub-package dcd:dsymbol is different than its parent package, this is discouraged.
    Starting Performing "release" build using ldc2 for x86_64.
  Up-to-date emsi_containers 0.9.0: target for configuration [library] is up to date.
    Building libdparse 0.25.0: building configuration [library]
    Building dcd:dsymbol 0.16.0-beta.3: building configuration [library]
  Up-to-date inifiled 1.3.3: target for configuration [library-quiet] is up to date.
  Up-to-date libddoc:common 0.8.0: target for configuration [library] is up to date.
    Building libddoc 0.8.0: building configuration [lib]
    Building dscanner 0.16.0-beta.4+commit.18.g3a87c65: building configuration [application]
   Pre-build Running commands
src\dscanner\analysis\mismatched_args.d(56,52): Error: no property `argNames` for `sym` of type `const(dsymbol.symbol.DSymbol)*`
```

https://github.com/dlang-community/D-Scanner/blob/master/src/dscanner/analysis/mismatched_args.d#L56

Offending PR: https://github.com/dlang-community/DCD/pull/763

**Comment by rikkimax** [comment]
Oh I see, DCD wasn't updated.

https://github.com/dlang-community/D-Scanner/blob/master/dub.selections.json#L4

**Comment by LightBender** [comment]
Are we waiting on anything to merge this?

**Comment by rikkimax** [comment]
Apart from the fact that if we did merge it, people who are not me are going to complain about it being broken?

Clone it, run dub upgrade on it, and try to build it. Just watch.

**Comment by pbackus** [comment]
DCD has already been updated upstream, so we should be good to go here once we upgrade the submodule and `dub.json`, right?

**Comment by thewilsonator** [comment]
What's the status of this? can we merge it. This is now holding up PRs.
