### ISSUE TITLE
Fail to build on Debian7 x64 with dmd 2.065.0

### ISSUE THREAD

**Issue by elvisxzhou** [dlang-community/D-Scanner#155]
./build.sh produce following errors

analysis/run.d(58) : Error: undefined identifier ParseAllocator
analysis/run.d(58) : Error: undefined identifier ParseAllocator
